/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('email_list').del()
  await knex('email_list').insert([
    { id: 1, email: 'alice.johnson@example.com'},
    { id: 2, email: 'bob.smith@example.com'},
    { id: 3, email: 'emily.brown@example.com'},
    { id: 4, email: 'michael.davis@example.com'},
    { id: 5, email: 'olivia.miller@example.com'},
    { id: 6, email: 'william.wilson@example.com'},
    { id: 7, email: 'sophia.anderson@example.com'},
    { id: 8, email: 'james.taylor@example.com'},
    { id: 9, email: 'ava.martinez@example.com'},
    { id: 10, email: 'john.lee@example.com'},
    { id: 11, email: 'emma.hernandez@example.com'},
    { id: 12, email: 'liam.clark@example.com' },
    { id: 13, email: 'mia.thomas@example.com' },
    { id: 14, email: 'noah.scott@example.com' },
    { id: 15, email: 'isabella.rodriguez@example.com' },
    { id: 16, email: 'ethan.hill@example.com' },
    { id: 17, email: 'avery.green@example.com' },
    { id: 18, email: 'sophia.turner@example.com' },
    { id: 19, email: 'alexander.phillips@example.com' },
    { id: 20, email: 'scarlett.campbell@example.com' },
    { id: 21, email: 'ella.white@example.com' },
    { id: 22, email: 'carter.martinez@example.com' },
    { id: 23, email: 'grace.harris@example.com' },
    { id: 24, email: 'landon.thompson@example.com' },
    { id: 25, email: 'scarlett.lee@example.com' },
    { id: 26, email: 'daniel.hall@example.com' },
    { id: 27, email: 'victoria.mitchell@example.com' },
    { id: 28, email: 'henry.young@example.com' },
    { id: 29, email: 'aria.allen@example.com' },
    { id: 30, email: 'matthew.torres@example.com' },
    { id: 31, email: 'sofia.adams@example.com' },
    { id: 32, email: 'ryan.flores@example.com' },
    { id: 33, email: 'alexa.scott@example.com' },
    { id: 34, email: 'christopher.hill@example.com' },
    { id: 35, email: 'mila.lopez@example.com' },
    { id: 36, email: 'jonathan.king@example.com' },
    { id: 37, email: 'luna.wright@example.com' },
    { id: 38, email: 'nathan.mitchell@example.com' },
    { id: 39, email: 'zoe.jackson@example.com' },
    { id: 40, email: 'elijah.cooper@example.com' },
    { id: 41, email: 'chloe.turner@example.com' },
    { id: 42, email: 'wyatt.morgan@example.com' },
    { id: 43, email: 'aubrey.hill@example.com' },
    { id: 44, email: 'grayson.diaz@example.com' },
    { id: 45, email: 'stella.wright@example.com' },
    { id: 46, email: 'levi.brooks@example.com' },
    { id: 47, email: 'samantha.price@example.com' },
    { id: 48, email: 'owen.bell@example.com' },
    { id: 49, email: 'hannah.murphy@example.com' },
    { id: 50, email: 'jackson.jenkins@example.com' },
    { id: 51, email: 'avery.reed@example.com' },
    { id: 52, email: 'lucas.cooper@example.com' },
    { id: 53, email: 'lily.perez@example.com' },
    { id: 54, email: 'aiden.howard@example.com' },
    { id: 55, email: 'zoe.rivera@example.com' },
    { id: 56, email: 'eli.simmons@example.com' },
    { id: 57, email: 'addison.hayes@example.com' },
    { id: 58, email: 'eleanor.ward@example.com' },
    { id: 59, email: 'gabriel.henderson@example.com' },
    { id: 60, email: 'brooklyn.foster@example.com' },
  ]);
}